### ISSUE TITLE
Problem With gulp serve in window

### ISSUE THREAD

**Issue by jay-thanki** [start-angular/ani-theme#11]
D:\xampp\htdocs\ani-theme\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (D:\xampp\htdocs\ani-theme\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\xampp\htdocs\ani-theme\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:635:30)

**Comment by fadziljusri** [comment]
It is because **process.EventEmitter is deprecated** in latest Node.js releases. To use gulp (serve, build, etc..) for this template you need to downgrade to node version 6.x.x , or you can use [nvm](https://github.com/coreybutler/nvm-windows) for windows and use node 6.x.x instead.
