### ISSUE TITLE
Problem with Gulp serve

### ISSUE THREAD

**Issue by cooligc** [start-angular/ani-theme#7]
Hi 

I have installed bower, npm . And worked fine.

When I am trying to do gulp serve , at the same time I am getting the below error...

/Users/MyUser/Downloads/ani-theme-master/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/sitakant/Downloads/ani-theme-master/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sitakant/Downloads/ani-theme-master/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

For Information:

OS : Mac OS Sierra
npm version : 4.0.5
gulp version : 3.9.1
bower version : 1.8.0

**Comment by ParkourKarthik** [comment]
I'm also facing the same issue. Followed the sequence as told in the readme.
`gulp serve` produces the same error for me as well.

Environment:
OS: Windows 10
npm version : 4.5.0
gulp version : 3.9.1
bower version : 1.8.0

**Comment by De-Lac** [comment]
update Karma
```
npm uninstall karma
npm install karma --save
```

**Comment by fadziljusri** [comment]
See [#11](https://github.com/start-angular/ani-theme/issues/11)
