### ISSUE TITLE
Glup serve is not working on ubntu

### ISSUE THREAD

**Issue by sumiodz** [start-angular/ani-theme#8]
gulp serve
/var/www/html/ani-theme/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/var/www/html/ani-theme/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/ani-theme/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
I have downgrade npm version 3.10.7 still not working

**Comment by jmperez127** [comment]
I was having the same error with node's version 7. I installed v6.9.1 through nvm and it worked.
